### ISSUE TITLE
[Quesntion] When can I see config file?

### ISSUE THREAD

**Issue by chagmgang** [ViTAE-Transformer/Remote-Sensing-RVSA#1]
Thank you for your contribution of deep learning research remote sensing field.
I'm very happy to find your research about self supervised learning in remote sensing field.

But I want to know about your config file of detection in dota and dior dataset.
Regards,
Kevin Cha.

**Comment by DotWang** [comment]
@chagmgang Hi, the [VSA](https://github.com/ViTAE-Transformer/ViTAE-VSA), which is the foundation of our RVSA, have already been released, while the codes, training logs of the RVSA will be uploaded in a few days.

Thanks for your attention to our work!

**Comment by chagmgang** [comment]
Thank you for answering.
Still waiting for RVSA config.
Thank you for your research.
@DotWang

**Comment by DotWang** [comment]
@chagmgang We have released the configs, thanks for your interest in our work!

**Comment by chagmgang** [comment]
@DotWang  Thank you.
