### ISSUE TITLE
Can I know about class wise IoU detail performance in LoveDA?

### ISSUE THREAD

**Issue by chagmgang** [ViTAE-Transformer/Remote-Sensing-RVSA#12]
I want to refer your paper in my research.
However, there are no class wise IoU detail performance of LoveDA semantic segmentation task, in both your paper and log file.

Thank you .

**Comment by DotWang** [comment]
@chagmgang  LoveDA is evaluated online, and the detailed results are only visible to individuals.

Here are our results for reference:

<html>
<body>
<h3 style="color: rgb(238, 236, 234); font-family: &quot;Microsoft YaHei&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Test results of your submission on LoveDA</h3>

Class | IoU
-- | --
mIoU | 0.524384915829
background | 0.466894805431
building | 0.581396400928
road | 0.57122862339
water | 0.796578943729
barren | 0.165543705225
forest | 0.464645594358
agriculture | 0.624406218529
ExecutionTime | 196.51863122


</body>
</html>

**Comment by chagmgang** [comment]
Thank you
