### ISSUE TITLE
Examples of train_labels.txt and valid_labels.txt files

### ISSUE THREAD

**Issue by nice7875** [ViTAE-Transformer/Remote-Sensing-RVSA#15]
Hello,  if it is possible could you provide an example of nengtrain_labels.txt and valid_labels.txt files in Classification. I can't find the previous version mentioned in Readme.

Thank you very much.

**Comment by DotWang** [comment]
@nice7875 for unsupervised pretraining, you only need to record the filename, as readme says

The example can be found in https://github.com/ViTAE-Transformer/RSP/blob/main/Scene Recognition/README.md

**Comment by nice7875** [comment]
Oh, I found it. Thank you for your response.
