### ISSUE TITLE
Missing script: tools/test.py file missing for segmentation and detection

### ISSUE THREAD

**Issue by utkutpcgl** [ViTAE-Transformer/Remote-Sensing-RVSA#25]
Thank you for your contribution!

I could not find the test.py file to run inference for detection or segmentation as mentioned in your README.md. Can you share it or do you not share it intentionally?

Regards.

**Comment by DotWang** [comment]
@utkutpcgl please see the readme, this repo only provide the codes of configs and models, the whole framework is in https://github.com/ViTAE-Transformer/RSP

**Comment by utkutpcgl** [comment]
Thank you very much, I have missed that ...

**Comment by utkutpcgl** [comment]
Thank you very much, I have missed that ...
