### ISSUE TITLE
Clarification about installation for segmentation

### ISSUE THREAD

**Issue by androbaza** [ViTAE-Transformer/Remote-Sensing-RVSA#5]
Hi, thank you for an amazing model. I'm trying to install the model over the clean mmsegmentation installed from their repo. 
 https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA/blob/0c67c1e38869fea89216c456232c928df4a3c116/Readme.md?plain=1#L220
I've put all of the files from Semantic Segmentation folder to the root of my mmsegmentation installation. Should I do `pip install -v -e .` again after I added the new files from your repo to mmsegmentation folder?

Also, please indicate where to put the files from `Semantic Segmentation/mmcv_custom`. Do we just leave it at mmsegmentation folder root? Or we should install mmcv from source?

**Comment by DotWang** [comment]
@androbaza 
Q: Should I do pip install -v -e . again after I added the new files from your repo to mmsegmentation folder?
A: Probably not, but it doesn't matter to reinstall. 
Q: Do we just leave it at mmsegmentation folder root?
A: Yes, please see https://github.com/ViTAE-Transformer/ViTPose
Q: Or we should install mmcv from source?
A: No, unless there is a version problem.

**Comment by androbaza** [comment]
> 

Thank you. The libraries seem to be in order, but I still can not properly start training -- the last error that I got was "could not find suitable CuDNN function to do convolution", despite that I have cuDNN installed. I will try to debug it once more, and will return with proper log, if I fail.

**Comment by DotWang** [comment]
@androbaza What's your GPU memory? Maybe the batchsize is too large, you can try to reduce it.

**Comment by androbaza** [comment]
> 

It is 24Gb. I monitor it as I start training, it does not go further than 11Gb. The batch size is 2. Usually it throws 'out of memory' error, when the memory is really the issue.

**Comment by DotWang** [comment]
@androbaza  emm...I have not encountered similar problems. If it is not the issue of batch size, it probably due to incompatible versions. Please check the versions of Pytorch, CUDA Toolkit and cuDNN.

**Comment by androbaza** [comment]
I reinstalled it again using the older mmseg version from https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing

The last time I also got error `No module named 'mmseg.models.backbones.ViTAE_DeformWindow_NoShift_v1` during `from mmseg.models import build_segmentor`, but I just commented the line as this file was not mentioned anywhere in you organization. Is it important one, or should that line be deleted?

https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA/blob/499b592d39545068634b61f08eeec774910e207a/Semantic%20Segmentation/mmseg/models/backbones/__init__.py#L24

**Comment by androbaza** [comment]
> @androbaza emm...I have not encountered similar problems. If it is not the issue of batch size, it probably due to incompatible versions. Please check the versions of Pytorch, CUDA Toolkit and cuDNN.

You were right about the versions. Thank you very much for your help. The training has started successfully.
