### ISSUE TITLE
UCM dataset train/test split.

### ISSUE THREAD

**Issue by pUmpKin-Co** [ViTAE-Transformer/Remote-Sensing-RVSA#7]
Could you please provide the txt file taht split the UCM dataset or is there an official way to split the dataset?

**Comment by DotWang** [comment]
@pUmpKin-Co  All classification datasets need to be split manually. We split them randomly.

**Comment by pUmpKin-Co** [comment]
> @pUmpKin-Co All classification datasets need to be split manually. We split them randomly.

Get! Thanks.
